### ISSUE TITLE
Uploading IIIF Images into Recogito

### ISSUE THREAD

**Issue by ChiaraPalladino** [pelagios/recogito2#441] opened 2017-11-29 19:30 UTC
A question from Ethan Gruber here: how do we upload IIIF images into Recogito? Is it possible to do that without downloading them?

**Comment by ewg118** [comment] 2017-11-29 19:36
@ewg118

**Comment by rsimon** [comment] 2017-11-29 19:38
You need to drag the URL of the image's info.json into the upload box. There's no need to upload any image. Note that __only__ image URLs are supported at the moment, not URLs to collection manifests.

It will all become more comfortable to use... in the next funding round ;-)

**Comment by ewg118** [comment] 2017-11-29 19:53
I did get it working in Chrome, but the drag and drop URL doesn't function the same way in Firefox.

**Comment by rsimon** [comment] 2017-11-30 07:36
Good to know. I'll look into that. We'll redesign the personal home/index page in the next round though, so the process should become a lot more usable overall.

**Comment by mromanello** [comment] 2018-02-16 16:25
I'm trying to get this to work too, but if I drag this `info.json` URL <https://images.center/iiif/402d6768-3cfd-416a-a5d0-f06722db7057-000001/info.json> into the box that says "drag files here", just nothing happens.

Am I missing something, or doing something wrong? thanks in advance!

**Comment by rsimon** [comment] 2018-02-20 11:56
Hm. Seems to be a regression... I can reproduce it. I'm putting it on the list for the March development phase. IIIF hasn't seen much love yet in Recogito. We're definitely determined to chang that soon-ish.

**Comment by mromanello** [comment] 2018-02-20 14:37
thanks @rsimon ! very interesting also to hear about the (lack ok) love for IIIF in your specific community. 

In most of our projects it's a key asset, and I do see the ability of plugging into Recogito any IIIF endpoint as a big plus (not to say a killer feature ;-) ). Especially because in some cases -- due to copyright constraints -- the endpoint is public but users are not allowed to directly download images... 

and thanks for putting this back into the development agenda of Recogito, much appreciated!

**Comment by rsimon** [comment] 2018-02-20 14:44
Not lack of love in our community, just too much to pack into the development schedule ;-) 

Arguably, though, our current activity has been focusing more on text, rather than images. In March & April, I do aim to catch up on this at least a little bit (see https://github.com/pelagios/recogito2/milestone/22).

Can I ask about what your current interest is? I'm really interested to hear what people are doing (are would like to do) with Recogito.

**Comment by efi** [comment] 2018-03-09 10:53
My (perspectively) planned usecase would include loading a bunch of maps from the David Rumsey Map Collection into recogito. For that I can live without manifest parsing (#276),

For stress testing puroses (which may also be useful for your new drawing / image annotation tools) I would be happy to have this monster imported: https://www.davidrumsey.com/luna/servlet/detail/RUMSEY~8~1~303661~90074314

The `info.json` can be obtained here: https://www.davidrumsey.com/luna/servlet/iiif/RUMSEY~8~1~303661~90074314/info.json

At the moment all I get after drag&drop of the downlaoded `info.json` is:
```
9.8 KB info.json
Unknown or unsupported file format
```

**Comment by rsimon** [comment] 2018-03-09 14:06
Yep, sorry for this. IIIF "upload" is currently broken. But will be fixed alongside the batch of updates that will be coming soon-ish for image annotation. (Collection manifest parsing won't be in the first wave. But is definitely scheduled as well.)

**Comment by rsimon** [comment] 2018-03-21 14:39
@efi hm, the Rumsey example is interesting. Their image server seems to speak yet another dialect that's not compatible with the KlokanTech IIIF client code. I'll need to investigate (and Klokan might have updated in the mean time). Anyways: uploading info.json's now works again __iff__ they are served via HTTPS, and the image API dialect on the image server fulfills certain criteria I have yet to figure out... - But I'm now shifting work to IIIF support, so stay tuned :-)

**Comment by rsimon** [comment] 2018-03-23 08:54
@efi I tried to dig into the Rumsey image a bit. It seems their map server doesn't support scaling part of the IIIF image API...

While this works:
https://www.davidrumsey.com/luna/servlet/iiif/RUMSEY~8~1~303661~90074314/30000,3000,500,500/full/0/default.jpg

This (which should return the same thing, downsized to 50%) doesn't:
https://www.davidrumsey.com/luna/servlet/iiif/RUMSEY~8~1~303661~90074314/30000,3000,500,500/pct:50/0/default.jpg

Whereas it should if I'm reading the [spec](http://iiif.io/api/image/2.1/#size) correctly.

Once you want to start working on this, I think we should simply get in touch with them. (We visited the Rumsey Map Center last December, I'm happy to dig up the contacts.)

**Comment by efi** [comment] 2018-03-23 09:31
@rsimon very strange!

It seems to parse the `pct:` directive correctly and then mess things up - if an invalid size string is submitted (or `0%` is requested), it gives a completely different error page. So I guess the support is there, the program is just broken.

_(I would have been irritated if the server weren't at least in theory compatible with KlokanTech's client since they implemented the GeoReferencer at Rumsey's.)_

As for my use case: it is really only a very early idea, so not a pressing issue for me. Yet since this seems to be a bug, it should get reported!

**Closed** 2018-04-04 11:56 UTC
Labels: ImageAnnotation, in progress

**Comment by rsimon** [comment] 2018-04-04 12:25
Yes, it's on my list. I'd like to investigate it a little more. As you note above, it seems related to the `pct:` argument. Other clients don't seem to use this (but use the absolute size of the view image instead). I think Klokan requests `pct` because it seems to deliver a slightly smoother zooming experience. The least thing I want to check is whether there is any strict requirement for servers to even support `pct`-based requests. (If not it might be on my end to fall back to absolute size instead.)

**Comment by efi** [comment] 2018-04-04 12:41
Great!

I would like to take back what I said about the Georeferencer integration. For this Klokan uses their own image server (iiifhosting.com) to serve (copies of ?) the maps. This server can deal with percentage parameters (yet they use the `!w,h` notation).

So the Rumsey server seems to just be there for powering their "LUNA" browser - which is not that "smooth" when it comes to continuous scaling.

**Comment by martimpassos** [comment] 2021-08-23 14:46
Hello, are there plans to support collection manifests and/or v3 manifests?

**Comment by rsimon** [comment] 2021-08-23 15:00
There's no active development on Recogito at the moment. There's some activity on replacing the current image annotation interface with the OpenSeadragon viewer and [Annotorious](https://annotorious.com), which would mean better support for all image API versions. And perhaps simplify support for v3 presentation API. But that still would require someone to actively pick up and/or fund that work.
