### ISSUE TITLE
Canvas failing to display loaded images

### ISSUE THREAD

**Issue by docuracy** [pelagios/recogito2#688] opened 2021-03-14 10:40 UTC
We've noticed intermittent problems like that illustrated below, with pieces of the canvas image failing to display, despite seeming to have been loaded successfully from our Cantaloupe IIIF server. The problem is the same in both Chrome and Edge browsers, and on different devices and OSs. Can you think of any settings that we might need to adjust, please?

The problem occurs not only with images served from our own IIIF server but with those from other IIIF servers too - the third image below is served from http://hdl.handle.net/10107/1445608.

![image](https://user-images.githubusercontent.com/42514781/111065155-326c4900-84b0-11eb-939a-8422e6085075.png)
![image](https://user-images.githubusercontent.com/42514781/111065325-fc7b9480-84b0-11eb-95b0-1f30e0d0d4cb.png)
![image](https://user-images.githubusercontent.com/42514781/111065406-685dfd00-84b1-11eb-852f-d8c3a9520f51.png)

**Comment by rsimon** [comment] 2021-03-14 17:31
I've seen this before occasionally. I still think it *might* have something to do with the settings in the info.json manifest (image size, tile size, zoom levels, or particular combinations thereof).

Root cause however is that we're using OpenLayers for display, along with a IIIF implementation that's no longer maintained by the developer. (I've patched some things myself. But can't keep track of everything.)

The bad news is: we're not going to fix it investigate these errors. I'm simply lacking the time and IIIF know how. 

The longer term view is that we'll replace OpenLayers with OpenSeadragon in the future, which has the most complete and will maintained IIIF implementation of there. (Can't give an arrival date for this yet. We don't have all the drawing tools ported yet.)

**Comment by docuracy** [comment] 2021-03-15 09:10
Odd, isn't it? The canvas is failing with any tiles that are not square (in this case 512px), and so it is impossible to view the bottom or right-hand edge of any image whose dimensions at respective zoom levels are not an exact multiple of 512px. But that doesn't explain why it appears to be an _intermittent_ problem. Ho hum.

Thanks anyway for the explanation.

**Comment by docuracy** [comment] 2021-03-16 06:13
SOLUTION: We've experienced this problem in Chrome and Edge browsers, but (for now at least) **Firefox** seems to be immune.

**Comment by garrettdashnelson** [comment] 2021-08-10 23:21
Jumping on here to note that I've encountered this exact same problem, also loading IIIF from a Cantaloupe server. (e.g. https://collections.leventhalmap.org/search/commonwealth:z603vn07z/manifest.json).

I'm not familiar enough with Scala to debug, but I don't think it can exclusively be an OpenLayers issue. I use OL's native `ol/source/IIIF` class very regularly with this same image server, and I've never seen quite the same behavior of leaving some tiles off of the rendered OL canvas.

**Comment by rsimon** [comment] 2021-12-13 11:50
Fixed in the main branch now

**Closed by rsimon** 2021-12-13 11:50 UTC
